# Site settings
title: Charles Broskoski
email: cab@are.na
description: > # Programmer and small-business owner based in New York
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://broskoski.cab" # the base hostname & protocol for your site
twitter_username: broskoski
github_username:  broskoski

# Build settings
markdown: kramdown
